name: Ubuntu 20.04

on: push

jobs:
  build:
    strategy:
      matrix:
        config:
          - host: ubuntu-20.04
            name: gogcheck
            test: 1

    runs-on: ${{ matrix.config.host }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Optional osslsigncode
        run: brew install osslsigncode

      - name: Optional innoextract
        run: brew install innoextract

      - name: Optional coreutils
        run: brew install coreutils

      - name: Optional rar
        run: sudo apt-get install unrar

      - name: Tap Dir
        run: mkdir -p "$(brew --repo)/Library/Taps/$(dirname "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')"

      - name: Tap Link
        run: ln -s "$PWD" "$(brew --repo)/Library/Taps/$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')"

      - name: Taps
        run: brew tap

      - name: Info
        run: brew info "${{ matrix.config.name }}"

      - name: Install
        run: brew install -v "${{ matrix.config.name }}"

      - name: Installed
        run: brew info "${{ matrix.config.name }}"

      - name: Audit
        run: brew audit --except=file,specs "${{ matrix.config.name }}"

      - name: Test
        run: brew test "${{ matrix.config.name }}"
        if: matrix.config.test == 1
